import { useEffect, useState } from 'react';

import type { NextPage } from 'next';
import Head from 'next/head';
import { auth } from '../firebase';
import {
    collection,
    query,
    where,
    onSnapshot,
    orderBy,
} from 'firebase/firestore';
import { db } from '../firebase';
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';

const Home: NextPage = () => {
    const [lessons, setLessons] = useState<string[]>([]);
    const lessonsQuery = query(
        collection(db, 'lessons'),
        where('ownerId', '==', auth?.currentUser?.uid)
    );

    // Listening to all the lessons
    // Maybe should listen only messages

    return (
        <div>
            <Head>
                <title>U said what</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Header />

            <Sidebar />
        </div>
    );
};

export default Home;
