import { Button, IconButton, TextField } from '@mui/material';
import { useEffect, useState } from 'react';

import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import { auth } from '../firebase';
import ArrowCircleRightIcon from '@mui/icons-material/ArrowCircleRight';
import {
    collection,
    query,
    where,
    onSnapshot,
    orderBy,
} from 'firebase/firestore';
import { createLesson } from '../service/lessonApi';
import { useCollectionData } from 'react-firebase-hooks/firestore';
import { db } from '../firebase';

const Home: NextPage = () => {
    const [input, setInput] = useState('');
    const [lessons, setLessons] = useState<string[]>([]);
    const lessonsQuery = query(
        collection(db, 'lessons'),
        where('ownerId', '==', auth?.currentUser?.uid)
    );

    // Listening to all the lessons
    // Maybe should listen only messages
    useEffect(() => {
        const unsubscribe = onSnapshot(lessonsQuery, (snap) => {
            snap.docs.map((doc) => console.log(doc.data()));
            setLessons(snap.docs.map((doc) => doc.data().name));
        });

        return () => unsubscribe();
    }, []);

    const create = async () => {
        if (auth?.currentUser) {
            await createLesson(auth.currentUser.uid, input);
            return;
        }
        console.log('No user');
    };

    const logOut = () => {
        if (auth.currentUser) {
            auth.signOut();
        }
    };

    const lessonsDiv = lessons.map((lesson) => (
        <div key={lesson}>{lesson}</div>
    ));

    return (
        <div>
            <Head>
                <title>U said what</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Button onClick={logOut}>LogOut</Button>
            <TextField
                id='outlined-basic'
                label='Create lesson'
                variant='filled'
                onChange={(event) => setInput(event.target.value)}
            />
            <IconButton onClick={create} disabled={input.length === 0}>
                <ArrowCircleRightIcon fontSize='large'></ArrowCircleRightIcon>
            </IconButton>
            {lessonsDiv}
        </div>
    );
};

export default Home;
